# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXURxdMU0PkRkcM9J_Z3x7kjltFQtNBG
"""

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Fingerprint_Project/dataset /Altered-Easy"
print(os.listdir(folder_path)[:10]) 

dataset_path = "/content/drive/MyDrive/Fingerprint_Project/dataset /Altered-Easy/"

file_name = "143__M_Left_ring_finger_Obl.BMP"  
file_path = os.path.join(folder_path, file_name)

import cv2
import matplotlib.pyplot as plt

img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

if img is None:
    print("Image not loaded. Check spelling or extension.")
else:
    plt.imshow(img, cmap='gray')
    plt.title("Sample Fingerprint")
    plt.show()

import os
import cv2
import matplotlib.pyplot as plt

folder_path = "/content/drive/MyDrive/Fingerprint_Project/dataset /Altered-Easy"

files = os.listdir(folder_path)

for file_name in files[:5]:   
    if file_name.lower().endswith(".bmp"):  
        img_path = os.path.join(folder_path, file_name)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        if img is not None:
            plt.imshow(img, cmap='gray')
            plt.title(file_name)
            plt.show()

import cv2

img_resized = cv2.resize(img, (128, 128))  

img_normalized = img_resized / 255.0

features = img_normalized.flatten()
print("Feature vector length:", len(features))

import numpy as np
import os

folder_path = "/content/drive/MyDrive/Fingerprint_Project/dataset /Altered-Easy"
files = os.listdir(folder_path)

X = []  # features
y = []  # labels

for file_name in files[:50]:  
    if file_name.lower().endswith(".bmp"):
        img_path = os.path.join(folder_path, file_name)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is not None:
            img_resized = cv2.resize(img, (128, 128))
            img_normalized = img_resized / 255.0
            features = img_normalized.flatten()
            X.append(features)
            y.append("Altered-Easy")  

X = np.array(X)
y = np.array(y)
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))

import os
import cv2
import numpy as np

base_path = "/content/drive/MyDrive/Fingerprint_Project/dataset "
folders = ["Altered-Easy", "Altered-Medium", "Altered-Hard"]

X = []
y = []

for folder in folders:
    folder_path = os.path.join(base_path, folder)
    files = os.listdir(folder_path)
    for file_name in files[:50]:  
        if file_name.lower().endswith(".bmp"):
            img_path = os.path.join(folder_path, file_name)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img_resized = cv2.resize(img, (128, 128))
                img_normalized = img_resized / 255.0
                features = img_normalized.flatten()
                X.append(features)
                y.append(folder)  

from sklearn.model_selection import train_test_split

X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred, labels=folders))
print("Report:\n", classification_report(y_test, y_pred, labels=folders))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred, labels=folders)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=folders, yticklabels=folders)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix Heatmap")
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

models = {
    "k-NN (k=3)": KNeighborsClassifier(n_neighbors=3),
    "SVM (linear)": SVC(kernel="linear"),
    "Decision Tree": DecisionTreeClassifier()
}

accuracies = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies[name] = acc
    print(f"{name} Accuracy: {acc:.2f}")

plt.figure(figsize=(6,4))
plt.bar(accuracies.keys(), accuracies.values(), color=["blue","green","orange"])
plt.ylabel("Accuracy")
plt.title("Classifier Accuracy Comparison")
plt.ylim(0,1) 
plt.show()

plt.savefig("/content/drive/MyDrive/Fingerprint_Project/results /confusion_matrix.png")

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, labels=folders)

with open("/content/drive/MyDrive/Fingerprint_Project/results /classification_report.txt", "w") as f:
    f.write(report)

import pandas as pd

results = pd.DataFrame({
    "Model": list(accuracies.keys()),
    "Accuracy": list(accuracies.values())
})

results.to_csv("/content/drive/MyDrive/Fingerprint_Project/results /model_accuracies.csv", index=False)

import os
import matplotlib.pyplot as plt

# Base results folder
results_path = "/content/drive/MyDrive/Fingerprint_Project/results "

# Ensure folder exists
os.makedirs(results_path, exist_ok=True)

def save_plot(filename):
    """Save the current matplotlib plot into results folder."""
    full_path = os.path.join(results_path, filename)
    plt.savefig(full_path, bbox_inches="tight")
    print(f"Plot saved: {full_path}")

def save_text(filename, content):
    """Save text output (reports, metrics) into results folder."""
    full_path = os.path.join(results_path, filename)
    with open(full_path, "w") as f:
        f.write(content)
    print(f"Text saved: {full_path}")

# Example: confusion matrix heatmap
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=folders, yticklabels=folders)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix Heatmap")

save_plot("confusion_matrix.png")  
plt.show()

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, labels=folders)
save_text("classification_report.txt", report)

plt.figure(figsize=(6,4))
plt.bar(accuracies.keys(), accuracies.values(), color=["blue","green","orange"])
plt.ylabel("Accuracy")
plt.title("Classifier Accuracy Comparison")
plt.ylim(0,1)

save_plot("accuracy_comparison.png")
plt.show()

import pandas as pd
from datetime import datetime

results_path = "/content/drive/MyDrive/Fingerprint_Project/results "

def log_results(model_name, params, accuracy):
    """Append experiment results into a CSV log file with timestamp."""
    log_file = os.path.join(results_path, "experiment_log.csv")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Create a DataFrame row
    df = pd.DataFrame([{
        "Timestamp": timestamp,
        "Model": model_name,
        "Parameters": params,
        "Accuracy": accuracy
    }])

    if not os.path.exists(log_file):
        df.to_csv(log_file, index=False)
    else:
        df.to_csv(log_file, mode="a", header=False, index=False)

    print(f"Logged: {model_name} | Accuracy: {accuracy:.2f}")
# Example: k-NN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)

log_results("k-NN", "n_neighbors=3", acc)
# Example: SVM
svm = SVC(kernel="linear")
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
acc = accuracy_score(y_test, y_pred)

log_results("SVM", "kernel=linear", acc)
pd.read_csv("/content/drive/MyDrive/Fingerprint_Project/results /experiment_log.csv")
import pandas as pd
import matplotlib.pyplot as plt

log_file = "/content/drive/MyDrive/Fingerprint_Project/results /experiment_log.csv"
df = pd.read_csv(log_file)
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
plt.figure(figsize=(8,5))

for model in df["Model"].unique():
    subset = df[df["Model"] == model]
    plt.plot(subset["Timestamp"], subset["Accuracy"], marker="o", label=model)

plt.xlabel("Experiment Time")
plt.ylabel("Accuracy")
plt.title("Accuracy Trends Across Experiments")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("/content/drive/MyDrive/Fingerprint_Project/results /accuracy_trends.png")
plt.show()

save_plot("filename.png")

import os

folder_path = "/content/drive/MyDrive/Fingerprint_Project/dataset /Altered-Easy"
print(os.listdir(folder_path)[:20]) 

count = len([f for f in os.listdir(folder_path) if f.lower().endswith((".bmp",".png",".jpg",".tif"))])

import os

folders = ["Altered-Easy", "Altered-Medium", "Altered-Hard"]
base_path = "/content/drive/MyDrive/Fingerprint_Project/dataset "  

total_images = 0
for folder in folders:
    folder_path = os.path.join(base_path, folder)
    files = [f for f in os.listdir(folder_path) if f.lower().endswith((".bmp",".png",".jpg",".tif"))]
    count = len(files)
    print(f"{folder}: {count} images")
    total_images += count

print(f"Total images used: {total_images}")